branch-defaults:
  master:
    environment: dockerNancy-env
global:
  application_name: docker-nancy
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2014.09 v1.0.11 running Docker 1.3.3
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
