branch-defaults:
  master:
    environment: nancy-docker-dev
global:
  application_name: nancy-docker
  default_ec2_keyname: null
  default_platform: Docker 1.3.3
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
